services:
    app:
        build: .
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: dev
            DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}?serverVersion=8.0.32&charset=utf8mb4"
        depends_on:
            database:
                condition: service_healthy

    database:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
            start_period: 30s
        volumes:
            - database_data:/var/lib/mysql

volumes:
    database_data:
